# Setup
title:               'Dongsu Choi'
tagline:             'Exploring Robotics and Bioelectronics'
description:         'I am a 4th-year Mechanical Engineering student at Seoul National University, focusing on robotics and bioelectronics. This is my personal website where I share my projects and research.'
url:                 https://grayharibo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
paginate_path:       "blog/page:num/"
remote_name:         "poole/lanyon"

# About/contact
author:
  name:              Dongsu Choi
  url:               https://www.linkedin.com/in/dongsu-choi-55a8442a0/
  email:             dongsu.choi00@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics:    G-YEG04ED7EY



