# Setup
title:               'Jehan Yang'
tagline:             'Pursuing Work in Advanced Robotics'
description:         'I am a <b>PhD student at CMU</b > that works on healthcare robotics! This is my <b>personal website</b > where I hope to put impactful advice and ideas for aspiring robotics enthusiasts.'
url:                 https://jehanyang.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
paginate_path:       "blog/page:num/"
remote_name:         "poole/lanyon"

# About/contact
author:
  name:              Jehan Yang
  url:               https://twitter.com/jehanyang
  email:             jehanyang@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics:    G-VZP2NHHH8D
